#!/usr/bin/env python3
"""Generate ONOS netcfg from an expanded topology JSON file."""

import argparse
import json
from pathlib import Path

from build_topology import build_topology_from_template, load_topology_file


DEFAULT_PIPECONF = "org.onosproject.ngsdn-multirouter"


def strip_prefix(ip_prefix):
    return ip_prefix.split("/", 1)[0]


def device_uri(router_name):
    return f"device:bmv2:{router_name}"


def router_ports(topology, router_name):
    ports = set()
    for link in topology["links"]:
        for endpoint in ("left", "right"):
            if link[endpoint]["router"] == router_name:
                ports.add(link[endpoint]["port"])
    for host in topology["hosts"]:
        if host["router"] == router_name:
            ports.add(host["routerPort"])
    return sorted(ports)


def port_descriptions(topology, router_name):
    return {
        str(port): {
            "number": port,
            "name": f"{router_name}-p{port}",
            "enabled": True,
            "type": "packet",
            "speed": 10000,
        }
        for port in router_ports(topology, router_name)
    }


def build_netcfg(topology, args):
    netcfg = {
        "devices": {},
        "ports": {},
        "links": {},
        "hosts": {},
        "apps": {
            "org.onosproject.core": {
                "core": {
                    "linkDiscoveryMode": "STRICT"
                }
            }
        }
    }

    for router in topology["routers"]:
        uri = device_uri(router["name"])
        netcfg["devices"][uri] = {
            "basic": {
                "name": router["name"],
                "driver": args.driver,
                "pipeconf": args.pipeconf,
                "managementAddress": (
                    f"grpc://{args.ip}:{router['grpcPort']}"
                    f"?device_id={router['deviceId']}"
                )
            },
            "fabricDeviceConfig": {
                "myStationMac": router["myStationMac"],
                "mySid": router["mySid"],
                "isSpine": False
            },
            "ports": port_descriptions(topology, router["name"])
        }

    for host in topology["hosts"]:
        uri = device_uri(host["router"])
        port = host["routerPort"]
        netcfg["ports"][f"{uri}/{port}"] = {
            "interfaces": [
                {
                    "name": f"{host['router']}-{host['name']}",
                    "ips": [host["gateway"]]
                }
            ]
        }
        netcfg["hosts"][f"{host['mac']}/None"] = {
            "basic": {
                "name": host["name"],
                "ips": [strip_prefix(host["ip"])],
                "locations": [f"{uri}/{port}"]
            }
        }

    for link in topology["links"]:
        left = link["left"]
        right = link["right"]
        left_cp = f"{device_uri(left['router'])}/{left['port']}"
        right_cp = f"{device_uri(right['router'])}/{right['port']}"
        netcfg["links"][f"{left_cp}-{right_cp}"] = {
            "basic": {
                "type": "DIRECT"
            }
        }
        netcfg["links"][f"{right_cp}-{left_cp}"] = {
            "basic": {
                "type": "DIRECT"
            }
        }

    return netcfg


def load_or_build_topology(args):
    if args.topology_file:
        return load_topology_file(args.topology_file)
    return build_topology_from_template(
        args.routers,
        args.hosts_per_router,
        args.topology,
        grpc_base=args.grpc_base,
        device_id_base=args.device_id_base,
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--ip", default="127.0.0.1",
                        help="Address ONOS uses to reach simple_switch_grpc")
    parser.add_argument("--topology-file",
                        help="Expanded topology JSON generated by build_topology.py")
    parser.add_argument("--routers", type=int, default=2)
    parser.add_argument("--hosts-per-router", type=int, default=1)
    parser.add_argument("--topology", choices=("linear", "ring", "mesh"),
                        default="linear")
    parser.add_argument("--grpc-base", type=int, default=9559)
    parser.add_argument("--device-id-base", type=int, default=0)
    parser.add_argument("--driver", default="bmv2")
    parser.add_argument("--pipeconf", default=DEFAULT_PIPECONF)
    parser.add_argument("--output", default="netcfg.json")
    args = parser.parse_args()

    try:
        topology = load_or_build_topology(args)
    except ValueError as exc:
        raise SystemExit(str(exc))

    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(build_netcfg(topology, args), indent=2) + "\n")
    print(f"Wrote {output}")


if __name__ == "__main__":
    main()
