#!/usr/bin/env python3
# Copyright 2013-present Barefoot Networks, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

"""
Multi-router network with P4Runtime/ONOS support.
Creates a ring topology with 10+ routers, each with a host attached.
Switches connect to ONOS controller via P4Runtime gRPC.
(Modified for Native IPv6 and SRv6 support)
"""

from mininet.net import Mininet
from mininet.topo import Topo
from mininet.node import Switch
from mininet.link import TCLink
from mininet.log import setLogLevel, info, error, debug
from mininet.moduledeps import pathCheck
from mininet.cli import CLI
from p4_mininet import P4Host

import argparse
import json
from time import sleep
import os
from pathlib import Path
import sys
import tempfile
import socket
import shlex
import subprocess
import signal
import time

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SW_PATH = "/usr/bin/simple_switch_grpc"
DEFAULT_JSON_PATH = str(PROJECT_ROOT / "p4build/ngsdn_tutorial/ngsdn_tutorial.json")
DEFAULT_P4INFO_PATH = str(PROJECT_ROOT / "p4build/ngsdn_tutorial.p4info.pb.txt")

parser = argparse.ArgumentParser(description='Multi-router P4Runtime/ONOS network (IPv6)')
parser.add_argument('--grpc-exe', help='Path to simple_switch_grpc executable',
                    type=str, action="store", default=DEFAULT_SW_PATH)
parser.add_argument('--json', help='Path to JSON config file',
                    type=str, action="store", default=DEFAULT_JSON_PATH)
parser.add_argument('--p4info', help='Path to P4Info protobuf file',
                    type=str, action="store", default=DEFAULT_P4INFO_PATH)
parser.add_argument('--thrift-port-base', help='Base Thrift server port',
                    type=int, action="store", default=9090)
parser.add_argument('--grpc-port-base', help='Base gRPC server port',
                    type=int, action="store", default=9559)
parser.add_argument('--num-routers', help='Number of routers',
                    type=int, action="store", default=10)
parser.add_argument('--num-hosts-per-router', help='Number of hosts per router',
                    type=int, action="store", default=1)
parser.add_argument('--topology', choices=['linear', 'ring', 'mesh'],
                    type=str, default='ring')
parser.add_argument('--topology-file',
                    help='Expanded topology JSON generated by tools/build_topology.py',
                    type=str, action="store", default=None)
parser.add_argument('--link-bw',
                    help='Mininet link bandwidth in Mbit/s, passed to TCLink bw',
                    type=float, action="store", default=None)
parser.add_argument('--link-delay',
                    help="Mininet link delay, e.g. '5ms' or '100us', passed to TCLink delay",
                    type=str, action="store", default=None)
parser.add_argument('--onos-ip', help='ONOS controller IP address',
                    type=str, action="store", default="127.0.0.1")
parser.add_argument('--cpu-port', help='CPU port number',
                    type=int, action="store", default=255)
parser.add_argument('--device-id-base', help='Base device ID',
                    type=int, action="store", default=0)
parser.add_argument('--pcap-dump', help='Dump packets to pcap files',
                    action='store_true', default=False)
parser.add_argument('--batch-json',
                    help='Run Mininet commands from a JSON batch file and exit',
                    type=str, action="store", default=None)
parser.add_argument('--batch-result',
                    help='Write batch execution result JSON to this path',
                    type=str, action="store", default=None)
parser.add_argument('--no-cli',
                    help='Do not enter the interactive Mininet CLI',
                    action='store_true', default=False)
parser.add_argument('--keep-running-after-batch',
                    help='Keep Mininet running after batch completion',
                    action='store_true', default=False)

args = parser.parse_args()
if args.link_bw is not None and args.link_bw <= 0:
    parser.error("--link-bw must be greater than 0")
if args.link_delay is not None and not args.link_delay.strip():
    parser.error("--link-delay must not be empty")
if args.batch_json and not args.batch_result:
    parser.error("--batch-result is required with --batch-json")


def router_mac(router_id):
    suffix = "{:04x}".format(router_id)
    return "00:aa:00:00:{}:{}".format(suffix[:2], suffix[2:])


def host_mac(router_index, host_index):
    return "00:04:00:00:{:02x}:{:02x}".format(router_index, host_index)


def template_links(num_routers, topology):
    links = []
    if topology == 'ring':
        for i in range(num_routers):
            links.append({'left': 'r{}'.format(i + 1),
                          'right': 'r{}'.format((i + 1) % num_routers + 1)})
    elif topology == 'linear':
        for i in range(num_routers - 1):
            links.append({'left': 'r{}'.format(i + 1),
                          'right': 'r{}'.format(i + 2)})
    elif topology == 'mesh':
        for i in range(num_routers):
            for j in range(1, 3):
                if i + j < num_routers:
                    links.append({'left': 'r{}'.format(i + 1),
                                  'right': 'r{}'.format(i + j + 1)})
    return links


def build_legacy_topology(num_routers, hosts_per_router, topology,
                          grpc_base, thrift_base, cpu_port, device_id_base):
    router_names = ['r{}'.format(i + 1) for i in range(num_routers)]
    next_port = {router: 1 for router in router_names}
    links = []

    for link in template_links(num_routers, topology):
        left = link['left']
        right = link['right']
        left_port = next_port[left]
        right_port = next_port[right]
        next_port[left] += 1
        next_port[right] += 1
        links.append({
            'left': {'router': left, 'port': left_port},
            'right': {'router': right, 'port': right_port},
        })

    hosts = []
    host_idx = 1
    for router_idx, router in enumerate(router_names):
        for host_idx_for_router in range(1, hosts_per_router + 1):
            port = next_port[router]
            next_port[router] += 1
            hosts.append({
                'name': 'h{}'.format(host_idx),
                'router': router,
                'routerPort': port,
                'mac': host_mac(router_idx, host_idx_for_router - 1),
                'ip': '2001:{}:{}::10/64'.format(
                    router_idx + 1, host_idx_for_router),
                'gateway': '2001:{}:{}::254/64'.format(
                    router_idx + 1, host_idx_for_router),
            })
            host_idx += 1

    routers = []
    for idx, router in enumerate(router_names):
        routers.append({
            'name': router,
            'deviceId': device_id_base + idx,
            'grpcPort': grpc_base + idx,
            'thriftPort': thrift_base + idx,
            'cpuPort': cpu_port,
            'myStationMac': router_mac(idx + 1),
            'mySid': 'fc00:0:{}::'.format(idx + 1),
        })
    return {
        'version': 1,
        'name': '{}-{}r-{}h'.format(topology, num_routers, hosts_per_router),
        'routers': routers,
        'links': links,
        'hosts': hosts,
    }


def load_topology(path):
    with open(path) as fp:
        topology = json.load(fp)
    if topology.get('version') != 1:
        raise ValueError("Unsupported topology version: {}".format(
            topology.get('version')))
    return topology


def link_options(link, default_link_opts):
    opts = dict(default_link_opts or {})
    if link.get('bw') is not None:
        opts['bw'] = link.get('bw')
    if link.get('delay') is not None:
        opts['delay'] = link.get('delay')
    return opts


def write_json_file(path, data):
    if not path:
        return
    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open('w') as fp:
        json.dump(data, fp, indent=2, sort_keys=True)
        fp.write("\n")


def touch_ready_file(path, topology_data):
    if not path:
        return
    write_json_file(path, {
        'ready': True,
        'topology': topology_data.get('name', 'unnamed'),
        'routers': len(topology_data['routers']),
        'hosts': len(topology_data['hosts']),
        'timestamp': time.time(),
    })


def wait_for_start_file(path, timeout_seconds):
    if not path:
        return True
    deadline = time.time() + timeout_seconds
    while time.time() < deadline:
        if os.path.exists(path):
            return True
        sleep(0.2)
    return False


def run_node_command(net, command_spec):
    node = net.get(command_spec['node'])
    command = command_spec['cmd']
    marker = '__MININET_BATCH_RC__='
    wrapped = "({}); rc=$?; printf '\\n{}%s\\n' \"$rc\"".format(
        command, marker)
    output = node.cmd("bash -lc {}".format(shlex.quote(wrapped)))

    rc = 127
    clean_lines = []
    for line in output.splitlines():
        if line.startswith(marker):
            try:
                rc = int(line[len(marker):])
            except ValueError:
                rc = 127
        else:
            clean_lines.append(line)

    expected = command_spec.get(
        'expectReturnCode',
        command_spec.get('expect_return_code'))
    passed = expected is None or rc == expected
    return {
        'name': command_spec.get('name', command),
        'node': command_spec['node'],
        'cmd': command,
        'returnCode': rc,
        'expectReturnCode': expected,
        'passed': passed,
        'output': "\n".join(clean_lines),
    }


def start_tcpdump(net, capture_spec):
    node = net.get(capture_spec['node'])
    output = capture_spec['output']
    Path(output).parent.mkdir(parents=True, exist_ok=True)

    cmd = [
        'tcpdump',
        '-i', capture_spec['interface'],
        '-U',
        '-w', output,
    ]
    packet_filter = capture_spec.get('filter')
    if packet_filter:
        cmd.extend(shlex.split(packet_filter))

    proc = node.popen(
        cmd,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.PIPE)
    sleep(capture_spec.get('startupSeconds', 0.5))

    started = proc.poll() is None
    stderr = ''
    if not started and proc.stderr:
        stderr = proc.stderr.read().decode('utf-8', errors='replace')

    return {
        'name': capture_spec.get('name', output),
        'node': capture_spec['node'],
        'interface': capture_spec['interface'],
        'output': output,
        'filter': packet_filter,
        'allowEmpty': capture_spec.get('allowEmpty', False),
        'process': proc,
        'started': started,
        'startupStderr': stderr,
    }


def stop_tcpdump(capture):
    proc = capture.pop('process')
    if proc.poll() is None:
        proc.terminate()
        try:
            proc.wait(timeout=5)
        except subprocess.TimeoutExpired:
            proc.kill()
            proc.wait(timeout=5)

    stderr = ''
    if proc.stderr:
        stderr = proc.stderr.read().decode('utf-8', errors='replace')

    capture['returnCode'] = proc.returncode
    capture['stderr'] = stderr
    capture['exists'] = os.path.exists(capture['output'])
    capture['size'] = os.path.getsize(capture['output']) if capture['exists'] else 0
    capture['passed'] = (
        capture['started'] and
        capture['exists'] and
        (capture['allowEmpty'] or capture['size'] > 24))
    return capture


def run_batch(net, topology_data, batch_path, result_path):
    with open(batch_path) as fp:
        batch = json.load(fp)

    result = {
        'passed': True,
        'commands': [],
        'captures': [],
        'errors': [],
    }

    touch_ready_file(batch.get('readyFile'), topology_data)

    start_file = batch.get('startFile')
    start_timeout = batch.get('startTimeoutSeconds', 180)
    if not wait_for_start_file(start_file, start_timeout):
        result['passed'] = False
        result['errors'].append(
            'Timed out waiting for start file {}'.format(start_file))
        write_json_file(result_path, result)
        return 1

    captures = []
    try:
        for capture_spec in batch.get('tcpdump', []):
            capture = start_tcpdump(net, capture_spec)
            captures.append(capture)
            if not capture['started']:
                result['passed'] = False
                result['errors'].append(
                    'tcpdump failed for {} on {}: {}'.format(
                        capture['name'], capture['interface'],
                        capture['startupStderr'].strip()))

        sleep(batch.get('captureWarmupSeconds', 1))

        for command_spec in batch.get('commands', []):
            command_result = run_node_command(net, command_spec)
            result['commands'].append(command_result)
            if not command_result['passed']:
                result['passed'] = False

        sleep(batch.get('settleSeconds', 1))
    except Exception as exc:
        result['passed'] = False
        result['errors'].append(str(exc))
    finally:
        result['captures'] = [stop_tcpdump(capture) for capture in captures]
        for capture in result['captures']:
            if not capture.get('passed'):
                result['passed'] = False

    write_json_file(result_path, result)
    return 0 if result['passed'] else 1


def keep_running():
    should_stop = {'value': False}

    def handle_signal(signum, frame):
        should_stop['value'] = True

    signal.signal(signal.SIGTERM, handle_signal)
    signal.signal(signal.SIGINT, handle_signal)
    info("\nBatch completed; keeping Mininet running. Press Ctrl+C or kill this process to stop.\n")
    while not should_stop['value']:
        sleep(1)


class P4SwitchGrpc(Switch):
    """P4 virtual switch with P4Runtime/gRPC support."""
    device_id = 0

    def __init__(self, name, sw_path=None, json_path=None, p4info_path=None,
                 grpc_port=None, thrift_port=None, cpu_port=None,
                 device_id=None, pcap_dump=False,
                 log_console=False, verbose=False,
                 onos_ip="127.0.0.1", **kwargs):
        Switch.__init__(self, name, **kwargs)

        assert(sw_path)
        assert(json_path)
        pathCheck(sw_path)

        if not os.path.isfile(json_path):
            error("Invalid JSON file.\n")
            exit(1)

        self.sw_path = sw_path
        self.json_path = json_path
        self.p4info_path = p4info_path
        self.grpc_port = grpc_port
        self.thrift_port = thrift_port
        self.cpu_port = cpu_port
        self.verbose = verbose
        self.pcap_dump = pcap_dump
        self.log_console = log_console
        self.onos_ip = onos_ip
        logfile = "/tmp/p4s.{}.log".format(self.name)
        self.output = open(logfile, 'w')

        if device_id is not None:
            self.device_id = device_id
            P4SwitchGrpc.device_id = max(P4SwitchGrpc.device_id, device_id)
        else:
            self.device_id = P4SwitchGrpc.device_id
            P4SwitchGrpc.device_id += 1

    @classmethod
    def setup(cls):
        pass

    def check_switch_started(self, pid):
        import time
        timeout = 30
        start_time = time.time()
        while True:
            if not os.path.exists(os.path.join("/proc", str(pid))):
                return False
            if time.time() - start_time > timeout:
                return False
            sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            try:
                sock.settimeout(0.5)
                result = sock.connect_ex(("localhost", self.grpc_port))
            finally:
                sock.close()
            if result == 0:
                return True
            sleep(0.1)

    def start(self, controllers):
        info("Starting P4 switch {} with gRPC.\n".format(self.name))
        args = [self.sw_path]
        for port, intf in self.intfs.items():
            if not intf.IP():
                args.extend(['-i', str(port) + "@" + intf.name])

        if self.pcap_dump: args.append("--pcap")
        if self.thrift_port: args.extend(['--thrift-port', str(self.thrift_port)])
        args.extend(['--device-id', str(self.device_id)])
        if self.json_path: args.append(self.json_path)
        args.append("--")
        if self.grpc_port: args.extend(['--grpc-server-addr', "0.0.0.0:{}".format(self.grpc_port)])
        if self.cpu_port is not None: args.extend(['--cpu-port', str(self.cpu_port)])
        if self.log_console: args.append("--log-console")

        logfile = "/tmp/p4s.{}.log".format(self.name)
        info(' '.join(args) + "\n")

        pid = None
        with tempfile.NamedTemporaryFile() as f:
            self.cmd(' '.join(args) + ' >' + logfile + ' 2>&1 & echo $! >> ' + f.name)
            pid = int(f.read())
        debug("P4 switch {} PID is {}.\n".format(self.name, pid))

        sleep(0.5)

        if not self.check_switch_started(pid):
            error("P4 switch {} did not start correctly.\n".format(self.name))
            error("Check log at: {}\n".format(logfile))
            exit(1)
        info("P4 switch {} has been started.\n".format(self.name))

    def stop(self):
        self.output.flush()
        self.cmd('kill %' + self.sw_path)
        self.cmd('wait')
        self.deleteIntfs()

    def attach(self, intf):
        assert(0)

    def detach(self, intf):
        assert(0)


class MultiRouterP4Topo(Topo):
    def __init__(self, sw_path, json_path, p4info_path,
                 onos_ip, topology_data, pcap_dump, link_opts=None, **opts):
        Topo.__init__(self, **opts)
        link_opts = dict(link_opts or {})

        for router in topology_data['routers']:
            self.addSwitch(
                router['name'], sw_path=sw_path, json_path=json_path, p4info_path=p4info_path,
                grpc_port=router['grpcPort'], thrift_port=router['thriftPort'],
                cpu_port=router.get('cpuPort', args.cpu_port),
                device_id=router['deviceId'], onos_ip=onos_ip, pcap_dump=pcap_dump
            )

        for link in topology_data['links']:
            left = link['left']
            right = link['right']
            self.addLink(
                left['router'], right['router'],
                port1=left['port'], port2=right['port'],
                **link_options(link, link_opts))

        for host in topology_data['hosts']:
            self.addHost(host['name'], ip=None, mac=host['mac'])
            self.addLink(
                host['name'], host['router'],
                port2=host['routerPort'],
                **link_opts)


def main():
    if not os.path.exists(args.grpc_exe):
        error("simple_switch_grpc not found at: {}\n".format(args.grpc_exe))
        sys.exit(1)
    if not os.path.exists(args.json):
        error("JSON config not found at: {}\n".format(args.json))
        sys.exit(1)
    if not os.path.exists(args.p4info):
        error("P4Info not found at: {}\n".format(args.p4info))
        sys.exit(1)

    link_opts = {}
    if args.link_bw is not None:
        link_opts['bw'] = args.link_bw
    if args.link_delay is not None:
        link_opts['delay'] = args.link_delay

    try:
        if args.topology_file:
            topology_data = load_topology(args.topology_file)
        else:
            topology_data = build_legacy_topology(
                args.num_routers, args.num_hosts_per_router, args.topology,
                args.grpc_port_base, args.thrift_port_base, args.cpu_port,
                args.device_id_base)
    except ValueError as exc:
        error("{}\n".format(exc))
        sys.exit(1)

    info("Creating topology {} ({} routers, {} hosts)\n".format(
        topology_data.get('name', 'unnamed'),
        len(topology_data['routers']),
        len(topology_data['hosts'])))
    if link_opts:
        info("Link options: {}\n".format(
            ", ".join("{}={}".format(k, v) for k, v in sorted(link_opts.items()))))
    
    topo = MultiRouterP4Topo(
        sw_path=args.grpc_exe, json_path=args.json, p4info_path=args.p4info,
        onos_ip=args.onos_ip, topology_data=topology_data,
        pcap_dump=args.pcap_dump,
        link_opts=link_opts
    )

    net_kwargs = dict(topo=topo, host=P4Host, switch=P4SwitchGrpc, controller=None)
    if link_opts or any('bw' in link or 'delay' in link
                        for link in topology_data['links']):
        net_kwargs['link'] = TCLink
    net = Mininet(**net_kwargs)

    info("Starting network...\n")
    net.start()

    #
    info("Configuring hosts with Native IPv6...\n")
    for host_config in topology_data['hosts']:
        host = net.get(host_config['name'])
        intf_name = host.defaultIntf().name

        host.cmd("sysctl -w net.ipv6.conf.all.disable_ipv6=0")
        host.cmd("sysctl -w net.ipv6.conf.default.disable_ipv6=0")
        host.cmd("sysctl -w net.ipv6.conf.lo.disable_ipv6=0")
        host.cmd("sysctl -w net.ipv6.conf.{}.disable_ipv6=0".format(intf_name))

        host.cmd("ip addr flush dev {}".format(intf_name))

        ipv6_addr = host_config['ip']
        ipv6_gw = host_config['gateway'].split('/', 1)[0]

        host.cmd("ip -6 addr add {} dev {}".format(ipv6_addr, intf_name))
        host.cmd("ip -6 route add default via {}".format(ipv6_gw))

    info("\n=== Topology ===\n")
    for router in topology_data['routers']:
        info("Router {}: gRPC=localhost:{}, Thrift=localhost:{}\n".format(
            router['name'],
            router['grpcPort'], router['thriftPort']))

    info("\n=== Ready ===\n")
    info("{} routers with {} host(s) (IPv6 Enabled)\n".format(
        len(topology_data['routers']), len(topology_data['hosts'])))
    info("\nUse 'pingall6' or 'h1 ping6 2001:2:1::10' for specific tests\n")

    exit_code = 0
    try:
        if args.batch_json:
            exit_code = run_batch(
                net, topology_data, args.batch_json, args.batch_result)
            if args.keep_running_after_batch:
                keep_running()
        elif not args.no_cli:
            CLI(net)
    finally:
        net.stop()

    sys.exit(exit_code)


if __name__ == '__main__':
    setLogLevel('info')
    main()
